name: Release binaries
on:
  push:
    tags:
      - "b*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [macos-latest]
        platform: [x64]

    steps:
      - name: Clone
        uses: actions/checkout@v1

      - name: Dependencies
        run: |
          brew update
          brew install sdl2
      - name: Build
        run: |
          cd whisper.cpp
          make
          make main
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: whisper.cpp/main
          asset_name: whisper
          asset_content_type: application/octet-stream